export { default as TermsPage } from './TermsPage'
export { default as PrivacyPage } from './PrivacyPage'
export { default as CookiesPage } from './CookiesPage'
export { default as ReturnsPage } from './ReturnsPage'
export { default as FaqPage } from './FaqPage'
